### ISSUE TITLE
验证码识别

### ISSUE THREAD

**Issue by djh29** [Editi0/SYSU-HealthReport#2]
可以参考我借鉴你的项目部分，我修改成本地识别了

**Comment by Editst** [comment]
666，提个pr我更新一下呗

**Comment by djh29** [comment]
提交了，你看一下，感谢[CAS-captcha](https://github.com/Qjbtiger/CAS-captcha)项目的模型

**Comment by Editst** [comment]
merge了，看看明天运行怎么样

**Comment by Editst** [comment]
改了一下，测试能跑了

**Comment by djh29** [comment]
有问题再沟通
